### PR TITLE
Supporting ack in CheckResult

### PR DESCRIPTION
**Pull request by tosan88**
Needed for `aggregate-healthcheck`: https://github.com/Financial-Times/aggregate-healthcheck/tree/ack-support

### CODE REVIEW

**Comment by Zapadlo** [comment]
Are we moving away from FT spec with this? Do we care?

**Comment by tosan88** [comment]
I understood that we already have model changes that were not FT spec and we can extend it. @catalin-ilea can you please confirm this?

**Comment by catalin-ilea** [comment]
https://github.com/Financial-Times/go-fthealth/commit/2433be2586e0cb182eba2762907bfd8de819741c
Yes, we've done it before. As long as we're backwards compatible I think we're ok to do it.
@martingartonft ^^

**Comment by Zapadlo** [comment]
Fine, upvoting!

**Pull request merged**
